export const ALL_BOOKS_REQUEST = "ALL_BOOKS_REQUEST";
export const ALL_BOOKS_SUCCESS = "ALL_BOOKS_SUCCESS";
export const ALL_BOOKS_FAIL = "ALL_BOOKS_FAIL";

export const CREATE_BOOKS_REQUEST = "CREATE_BOOKS_REQUEST";
export const CREATE_BOOKS_SUCCESS = "CREATE_BOOKS_SUCCESS";
export const CREATE_BOOKS_FAIL = "CREATE_BOOKS_FAIL";
export const CREATE_BOOKS_RESET = "CREATE_BOOKS_RESET";

export const DELETE_BOOKS_REQUEST = "DELETE_BOOKS_REQUEST";
export const DELETE_BOOKS_SUCCESS = "DELETE_BOOKS_SUCCESS";
export const DELETE_BOOKS_FAIL = "DELETE_BOOKS_FAIL";
export const DELETE_BOOKS_RESET = "DELETE_BOOKS_RESET";

export const UPDATE_BOOKS_REQUEST = "UPDATE_BOOKS_REQUEST";
export const UPDATE_BOOKS_SUCCESS = "UPDATE_BOOKS_SUCCESS";
export const UPDATE_BOOKS_FAIL = "UPDATE_BOOKS_FAIL";
export const UPDATE_BOOKS_RESET = "UPDATE_BOOKS_RESET";

export const NEW_BOOKS_REQUEST = "NEW_BOOKS_REQUEST";
export const NEW_BOOKS_SUCCESS = "NEW_BOOKS_SUCCESS";
export const NEW_BOOKS_FAIL = "NEW_BOOKS_FAIL";

export const GET_BOOK_REQUEST = "GET_BOOK_REQUEST";
export const GET_BOOK_SUCCESS = "GET_BOOK_SUCCESS";
export const GET_BOOK_FAIL = "GET_BOOK_FAIL";

export const BOOK_REVIEW_REQUEST = "BOOK_REVIEW_REQUEST";
export const BOOK_REVIEW_SUCCESS = "BOOK_REVIEW_SUCCESS";
export const BOOK_REVIEW_FAIL = "BOOK_REVIEW_FAIL";
export const BOOK_REVIEW_RESET = "BOOK_REVIEW_RESET";

export const GET_REVIEW_REQUEST = "GET_REVIEW_REQUEST";
export const GET_REVIEW_SUCCESS = "GET_REVIEW_SUCCESS";
export const GET_REVIEW_FAIL = "GET_REVIEW_FAIL";

export const ADMIN_GET_BOOKS_REQUEST = "ADMIN_GET_BOOKS_REQUEST";
export const ADMIN_GET_BOOKS_SUCCESS = "ADMIN_GET_BOOKS_SUCCESS";
export const ADMIN_GET_BOOKS_FAIL = "ADMIN_GET_BOOKS_FAIL";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
